adds support for route names and http methods in the array for routes
starweb/flare-app pull request #1
Opened 2018-07-20 09:13 UTC by lordrhodos

This PR adds support for extended routing suport

* route names
* HTTP methods 

Background
---
The Startlit routing implementation based on the `symfony/routing` component is quite limited and supports only a subset of the features provided by the component:

* routing names are not supported
* can not configure multiple routes for the same `path`
* can not configure HTTP methods for routes

A new `Route` just gets added like this:

```
$this->addRoute(new Route($path, $defaults, $requirements);
```
supporting only `path`, `defaults` and `requirements`, but the `Route` constructor supports a lot more optional attributes which should be (fully?) supported:

```
/**
 * Constructor.
 *
 * Available options:
 *
 *  * compiler_class: A class name able to compile this route instance (RouteCompiler by default)
 *  * utf8:           Whether UTF-8 matching is enforced ot not
 *
 * @param string          $path         The path pattern to match
 * @param array           $defaults     An array of default parameter values
 * @param array           $requirements An array of requirements for parameters (regexes)
 * @param array           $options      An array of options
 * @param string          $host         The host pattern to match
 * @param string|string[] $schemes      A required URI scheme or an array of restricted schemes
 * @param string|string[] $methods      A required HTTP method or an array of restricted methods
 * @param string          $condition    A condition that should evaluate to true for the route to match
 */
public function __construct($path, array $defaults = array(), array $requirements = array(), array $options = array(), $host = '', $schemes = array(), $methods = array(), $condition = '')
```
On top of that Starlit does not allow route names, thus does not allow support for multiple routes using the same path (e.g. with different HTTP methods):

```
/**
  * Add route.
  *
  * @param Route $route
  */
 public function addRoute(Route $route)
 {
     // We use path as name (sees no use for names)
     $this->routes->add($route->getPath(), $route);
 }
```

2018-08-08 15:11 UTC, felixsand requested changes

2018-08-08 15:11 UTC, felixsand commented on src/Router.php
> +        $methods = isset($routeConfig['methods']) ? $routeConfig['methods'] : [Request::METHOD_GET];
Did you find anything regarding the default methods array here?
So that we still accept GET, POST, PUT, DELETE, etc as the default?

2018-08-09 07:53 UTC, lordrhodos commented
You were right, the methods should be initialized correctly with an empty `[]` if not configured otherweise. I was tricked by the default catchAll route you can find in https://github.com/starweb/starlit-app/blob/master/src/Router.php#L82

2018-08-09 08:55 UTC, felixsand requested changes
Excellent!
I found a couple of parts that maybe can improve readability some. What do you think?

2018-08-09 08:55 UTC, felixsand commented on tests/RouterTest.php
> +        $this->assertCount(3, $this->router->getRoutes());
This test can be easily broken by changes in other parts of this test. What do you think about the following approach instead:
```
$numberOfRoutes = count($this->router->getRoutes());
$this->router->addRoute($route, 'foo-bar');
$numberOfRoutes++;
$this->assertCount($numberOfRoutes, ($routes = $this->router->getRoutes()));
```

(same for `testAddRouteWithHttpMethods()`)

2018-08-09 08:55 UTC, felixsand commented on src/Router.php
> +                $name = $path;
The other way around would make a bit more sense here:

`... as $name => $routeConfig) {`

and then:
```
if (array_key_exists('path', $routeConfig)) {
    $path = $routeConfig['path'];
} else {
    $route = $name;
}
```

2018-08-09 09:10 UTC, lordrhodos commented
@felixsand fixed your change requests

2018-08-09 09:15 UTC, felixsand approved these changes
Excellent! 🎉

2018-08-09 11:18 UTC, andreasnij requested changes

2018-08-09 11:18 UTC, jandreasn commented on src/Router.php
> +                }
I think this if-logic would be better placed in the `addRouteFromConfig`-method. You could also rename the `$name` variable and the `$path` parameter to `$nameOrPath` to make the intent more clear.

2018-08-09 11:18 UTC, jandreasn commented on src/Router.php
> +     * @param string|null $route
Should be `$name`.

2018-08-09 11:18 UTC, jandreasn commented on src/Router.php
> +        if (null === $name) {
It was previously decided to avoid yoda notation in this code base 🙂

2018-08-09 11:34 UTC, henrikjon approved these changes
Looks good after the latest changes. 👍

2018-08-09 11:39 UTC, lordrhodos commented
@jandreasn thx for the feedback. I have pushed the updates.

2018-08-09 11:45 UTC, andreasnij approved these changes

2018-08-09 11:49 UTC, merged