Feature/reflection based dependency injection (#3)
starweb/flare-app pull request #4
Opened 2019-02-22 08:29 UTC by felixsand

* Updated dependencies to PHP >=7.1 and Symfony ^4.0
Updated starlit inter-package dependencies

* Updated Travis CI to run tests on PHP 7.1 and 7.2

* Fixed typo

* First version of reflection-based DI Container

* Readability and style fixes

* Refactored code to use new version of DI Container
Modified tests affected by code changes

* Code style fix

* Fixed incorrect parameter resolution

* Fixed resolution of classes without constructors

* Fixed resolution of classes without constructors

* Fixed resolution of unmapped interface parameters with default values

* Slight readability improvements

* Slight optimizations and improvements

* Slight optimizations and restructuring of code

* Removed fully qualified function calls

* Simplified test with mock object and expectations

* Added interfaces for Router and View
Changed class name strings into SomeClass::class constructs

* Added unset() and unalias() methods to Container

* Changed uses of Router to RouterInterface

* Allow null parameter to View::escape()

* Added alias check to Container::destroyInstance()

* Fixed test

2019-02-22 08:31 UTC, felixsand commented
Some remaining polishing remains. See: https://github.com/starweb/starlit-app/pull/3

2019-03-15 13:38 UTC, felixsand commented on src/ViewInterface.php
> + * @copyright Copyright (c) 2016 Starweb AB
```suggestion
 * @copyright Copyright (c) 2019 Starweb AB
```
Both here and in any new file

2019-03-15 13:38 UTC, felixsand commented on src/ViewInterface.php
> +     * Constructor.
Many unnecessary comments in this file. Would be nice to keep it a bit more slim and only comment where something is unclear or requires some additional info

2019-03-15 22:23 UTC, lordrhodos requested changes
I think we need to add interfaces for the abstract classes we use in return type declarations. Apart from that I see only smaller changes that need to be made.

2019-03-15 22:23 UTC, lordrhodos commented on src/Container/Container.php
> +    public function hasInstance($key): bool
```suggestion
    public function hasInstance(string $key): bool
```

and phpdoc can be removed

2019-03-15 22:23 UTC, lordrhodos commented on src/Container/Container.php
> +            throw new NotFoundException(sprintf('Key "%s" could not be resolved. ', $key));
```suggestion
            throw new NotFoundException(\sprintf('Key "%s" could not be resolved.', $key));
```

2019-03-15 22:23 UTC, lordrhodos commented on src/Container/Container.php
> +    public function destroyInstance($key): void
```suggestion
    public function destroyInstance(string $key): void
```

and phpdoc can be removed

2019-03-15 22:23 UTC, lordrhodos commented on src/RouterInterface.php
> + * @copyright Copyright (c) 2016 Starweb AB
```suggestion
 * @copyright Copyright (c) 2019 Starweb AB
```

2019-03-15 22:23 UTC, lordrhodos commented on src/RouterInterface.php
> +    public function route(Request $request): AbstractController;
This is a good start, but should be better implmented against a contract (interface)

2019-03-15 22:23 UTC, lordrhodos commented on src/ViewInterface.php
> +    public function setLayout(string $script);
do we have a mixed return value here or can we add a return type declaration?

2019-03-15 22:23 UTC, lordrhodos commented on src/ViewInterface.php
> +    public function getHelper(string $helperName): AbstractViewHelper;
same here, use an interface instead of the abstract class

2019-03-28 16:00 UTC, PaulPylkas reviewed
I think it might be better to modify `Container::resolveParameters` to be public and take an optional `array $overrideParameters` parameter. We can then send in `$this->request->attributes->all()` in `AbstractController`.

It's pretty much just a more generalized implementation of the same thing. What do you think?

2019-03-29 10:07 UTC, lordrhodos commented on src/Container/Container.php
> +    public function set(string $key, $value): self
```suggestion
    public function set($key, $value): self
```

2019-03-29 10:13 UTC, lordrhodos commented on src/Container/Container.php
> +    public function set(string $key, $value): self
@PaulPylkas can you check this, I think we need to remove the type declaration here or not?

2019-03-30 06:22 UTC, lordrhodos commented
@PaulPylkas I have changed the visibility for `Container::resolveInstance` to `private` as we do not need to expose it anymore.

2019-03-30 06:24 UTC, lordrhodos approved these changes
@PaulPylkas @felixsand Approved from my side. Let's get this merged into `1.0.x-dev` and apply the 1.0.0 fixes to that branch in dedicated PRs

2019-04-09 05:01 UTC, merged